image: cincproject/omnibus-debian
stages:
 - patch
 - package
 - test
 - deploy
 - publish
 - cleanup

variables:
  ORIGIN: https://github.com/chef/chef.git
  REF: master
  CHANNEL: unstable

client_patch:
  stage: patch
  tags:
    - osuosl
  script:
    - ./patch.sh
  artifacts:
    expire_in: 1d
    paths:
      - chef/
      - omnibus-software/

.client-package:
  stage: package
  tags:
    - osuosl
  dependencies:
    - client_patch
  script:
    - source /home/omnibus/load-omnibus-toolchain.sh
    - cd chef/omnibus
    - bundle install --without development --path ${CI_PROJECT_DIR}/bundle/vendor
    - bundle exec omnibus build cinc --override append_timestamp:false
    - mkdir ${CI_PROJECT_DIR}/data
    - mv -v pkg/cinc* ${CI_PROJECT_DIR}/data/
    - cp ../VERSION ${CI_PROJECT_DIR}/
  cache:
    paths:
      - cache/*
      - bundle/vendor/*
  artifacts:
    expire_in: 1mo
    paths:
      - data/*
      - VERSION

client-package:macos-10.14:
  extends: .client-package
  tags:
    - macos-10.14
  script:
    - source /Users/omnibus/load-omnibus-toolchain.sh
    - cd chef/omnibus
    - bundle install --without development --path ${CI_PROJECT_DIR}/bundle/vendor
    - sudo rm -rf /var/cache/omnibus/pkg/*
    - sudo bundle exec omnibus build cinc --override append_timestamp:false
    - mkdir -p ${CI_PROJECT_DIR}/data/mac_os_x/10.14
    - sudo chown -R omnibus:omnibus pkg
    - mv -v pkg/cinc*dmg* ${CI_PROJECT_DIR}/data/mac_os_x/10.14/
    - sudo bundle exec omnibus clean cinc
    - sudo rm -rf /opt/cinc/*
  cache:
    key: macos:10.14

client-package:macos-10.15:
  extends: .client-package
  tags:
    - macos-10.15
  script:
    - source /Users/omnibus/load-omnibus-toolchain.sh
    - cd chef/omnibus
    - bundle install --without development --path ${CI_PROJECT_DIR}/bundle/vendor
    - sudo rm -rf /var/cache/omnibus/pkg/*
    - /usr/local/bin/gsed -i "s:^cache_dir.*:cache_dir '/var/cache/omnibus/cache':" omnibus.rb
    - /usr/local/bin/gsed -i "s:^git_cache_dir.*:git_cache_dir '/var/cache/omnibus/git_cache':" omnibus.rb
    - sudo bundle exec omnibus build cinc --override append_timestamp:false
    - mkdir -p ${CI_PROJECT_DIR}/data/mac_os_x/10.15
    - sudo chown -R omnibus:omnibus pkg
    - mv -v pkg/cinc*dmg* ${CI_PROJECT_DIR}/data/mac_os_x/10.15/
    - sudo bundle exec omnibus clean cinc
    - sudo rm -rf /opt/cinc/*
  cache:
    key: macos:10.15

client-package:windows-2012r2:
  extends: .client-package
  tags:
    - windows-x64
  script:
    - $ErrorActionPreference = "Stop"
    - C:\omnibus\load-omnibus-toolchain.ps1
    - cd chef\omnibus
    - bundle install --without development --path ${CI_PROJECT_DIR}/bundle/vendor
    - bundle exec omnibus build cinc --override append_timestamp:false
    - mkdir.exe -p ${CI_PROJECT_DIR}/data/windows/2012r2
    - mv.exe -v pkg/cinc* ${CI_PROJECT_DIR}/data/windows/2012r2
    - bundle exec omnibus clean cinc
  cache:
    key: windows:2012r2

client-package:debian-8:
  extends: .client-package
  image: cincproject/omnibus-debian:8
  cache:
    key: debian:8
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/debian/8
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/debian/8/

client-package:debian-9:
  extends: .client-package
  image: cincproject/omnibus-debian:9
  cache:
    key: debian:9
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/debian/9
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/debian/9/

client-package:debian-10:
  extends: .client-package
  image: cincproject/omnibus-debian:10
  cache:
    key: debian:10
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/debian/10
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/debian/10/

client-package:ubuntu-16.04:
  extends: .client-package
  image: cincproject/omnibus-ubuntu:16.04
  cache:
    key: ubuntu:16.04
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/ubuntu/16.04
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/ubuntu/16.04/

client-package:ubuntu-18.04:
  extends: .client-package
  image: cincproject/omnibus-ubuntu:18.04
  cache:
    key: ubuntu:18.04
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/ubuntu/18.04
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/ubuntu/18.04/

client-package:centos-6:
  extends: .client-package
  image: cincproject/omnibus-centos:6
  cache:
    key: centos:6
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/el/6
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/el/6/

client-package:centos-7:
  extends: .client-package
  image: cincproject/omnibus-centos:7
  cache:
    key: centos:7
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/el/7
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/el/7/

client-package:centos-8:
  extends: .client-package
  image: cincproject/omnibus-centos:8
  cache:
    key: centos:8
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/el/8
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/el/8/

.client-test:
  stage: test
  tags:
    - osuosl
  script:
    - /opt/cinc/bin/cinc-client --version
    - /opt/cinc/bin/cinc-solo -l info
    - cinc-client --version
    - cinc-solo -l info
    - /opt/cinc/bin/chef-client --version
    - /opt/cinc/bin/chef-solo -l info
    - chef-client --version
    - chef-solo -l info
    - /opt/cinc/embedded/bin/cinc-zero --version

.client-test-windows:
  tags:
    - windows-x64
  before_script:
    - ./scripts/install-cinc.ps1
  script:
    - $ErrorActionPreference = "Stop"
    - $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
    - echo $env:PATH
    - C:\cinc-project\cinc\bin\cinc-client.bat --version
    - C:\cinc-project\cinc\bin\cinc-solo.bat -l info
    - cinc-client --version
    - cinc-solo -l info
    - C:\cinc-project\cinc\embedded\bin\cinc-zero.bat --version
  after_script:
    - ./scripts/uninstall-cinc.ps1

client-test:macos-10.14:
  extends: .client-test
  tags:
    - macos-10.14
  dependencies:
    - client-package:macos-10.14
  script:
    - sudo scripts/install-cinc-macos.sh
    - /opt/cinc/bin/cinc-client --version
    - sudo /opt/cinc/bin/cinc-solo -l info
    - cinc-client --version
    - sudo cinc-solo -l info
    - /opt/cinc/embedded/bin/cinc-zero --version
    - sudo scripts/uninstall-cinc-macos.sh

client-test:macos-10.15:
  extends: .client-test
  tags:
    - macos-10.15
  dependencies:
    - client-package:macos-10.15
  script:
    - sudo scripts/install-cinc-macos.sh
    - /opt/cinc/bin/cinc-client --version
    - sudo /opt/cinc/bin/cinc-solo -l info
    - cinc-client --version
    - sudo cinc-solo -l info
    - sudo scripts/uninstall-cinc-macos.sh

client-test:windows-2012r2:
  extends: .client-test-windows
  dependencies:
    - client-package:windows-2012r2

client-test:debian-8:
  extends: .client-test
  image: cincproject/omnibus-debian:8
  dependencies:
    - client-package:debian-8
  before_script:
    - dpkg -i data/debian/8/cinc*.deb
  after_script:
    - apt-get -y remove cinc

client-test:debian-9:
  extends: .client-test
  image: cincproject/omnibus-debian:9
  dependencies:
    - client-package:debian-9
  before_script:
    - dpkg -i data/debian/9/cinc*.deb
  after_script:
    - apt-get -y remove cinc

client-test:debian-10:
  extends: .client-test
  image: cincproject/omnibus-debian:10
  dependencies:
    - client-package:debian-10
  before_script:
    - dpkg -i data/debian/10/cinc*.deb
  after_script:
    - apt-get -y remove cinc

client-test:ubuntu-16.04:
  extends: .client-test
  image: cincproject/omnibus-ubuntu:16.04
  dependencies:
    - client-package:ubuntu-16.04
  before_script:
    - dpkg -i data/ubuntu/16.04/cinc*.deb
  after_script:
    - apt-get -y remove cinc

client-test:ubuntu-18.04:
  extends: .client-test
  image: cincproject/omnibus-ubuntu:18.04
  dependencies:
    - client-package:ubuntu-18.04
  before_script:
    - dpkg -i data/ubuntu/18.04/cinc*.deb
  after_script:
    - apt-get -y remove cinc

client-test:centos-6:
  extends: .client-test
  image: cincproject/omnibus-centos:6
  dependencies:
    - client-package:centos-6
  before_script:
    - yum -y install data/el/6/cinc*.rpm
  after_script:
    - yum -y remove cinc

client-test:centos-7:
  extends: .client-test
  image: cincproject/omnibus-centos:7
  dependencies:
    - client-package:centos-7
  before_script:
    - yum -y install data/el/7/cinc*.rpm
  after_script:
    - yum -y remove cinc


client-test:centos-8:
  extends: .client-test
  image: cincproject/omnibus-centos:8
  dependencies:
    - client-package:centos-8
  before_script:
    - yum -y install data/el/8/cinc*.rpm

.ssh-setup:
  before_script:
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

client-deploy:
  when: manual
  stage: deploy
  extends: .ssh-setup
  tags:
    - osuosl
  dependencies:
    - client-package:debian-8
    - client-package:debian-9
    - client-package:debian-10
    - client-package:ubuntu-16.04
    - client-package:ubuntu-18.04
    - client-package:centos-6
    - client-package:centos-7
    - client-package:centos-8
    - client-package:windows-2012r2
    - client-package:macos-10.14
    - client-package:macos-10.15
  script:
    - ssh cinc@${DOWNLOADS_HOST} "mkdir -p /data/incoming/files/${CHANNEL}/cinc/$(cat VERSION)"
    - rsync -avH --delete data/ cinc@${DOWNLOADS_HOST}:/data/incoming/files/${CHANNEL}/cinc/$(cat VERSION)/
    - ssh cinc@${DOWNLOADS_HOST} "chmod 755 /data/incoming/files/${CHANNEL}/cinc/$(cat VERSION)/"

client-publish:
  when: manual
  stage: publish
  extends: .ssh-setup
  dependencies: []
  tags:
    - downloads
  script:
    - sudo mkdir -p /data/mirror/files/${CHANNEL}/cinc
    - sudo /usr/bin/rsync -avH /data/incoming/files/${CHANNEL}/cinc/ /data/mirror/files/${CHANNEL}/cinc/
    - ssh -q cinc@${MIRROR_HOST} "~/sync-from-master"

.cleanup:
  stage: cleanup
  dependencies: []
  variables:
    GIT_CHECKOUT: "false"
  when: always
  script:
    - sudo rm -rf chef/

cleanup:macos-10.14:
  extends: .cleanup
  tags:
    - macos-10.14

cleanup:macos-10.15:
  extends: .cleanup
  tags:
    - macos-10.15
