image: "ruby:2.5"
stages:
 - patch
 - package

before_script:
  - ruby -v                                   # Print out ruby version for debugging
  
Cinc-patch:
  stage: patch
  script:
    - git clone --depth=1 https://github.com/chef/chef.git
    - apt-get update
    - apt-get install -y rename
    - rename 's/chef/cinc' chef/bin/*
    - cp -R cinc/* chef/
    - sed -i '/s.executables  =/ s/chef/cinc/g' chef.gemspec
    - ls chef/*
  artifacts:
    expire_in: 1d
    paths:
      - chef/
  
Cinc-package-deb:
  stage: package
  script:
    - apt-get update 
    - apt-get -y install git build-essential
    - gem install omnibus
    - cd chef/omnibus
    - bundle install --without development
    - bundle exec omnibus build cinc
    - ls -alh */*
    - mv pkg/*.deb $CI_PROJECT_DIR
  artifacts:
    expire_in: 1mo
    paths:
      - ./*.deb