image: "ruby:2.5"

before_script:
  - apt-get update 
  - ruby -v                                   # Print out ruby version for debugging
  
package:
  script:
    - apt-get -y install git build-essential
    - gem install omnibus
    - git clone --depth=1 https://github.com/chef/chef.git
    - cd chef/omnibus
    - bundle install
    - bundle exec omnibus build chef
    - ls -alh */*    

artifacts:
  paths:
   - pkg/*.deb